import '../models/insurance_interval_model.dart';
import '../../core/config/supabase_config.dart';
import '../../core/config/database_schema.dart';

class InsuranceIntervalRepository {
  final _client = SupabaseConfig.client;

  /// Get insurance interval for a specific car
  Future<InsuranceIntervalModel?> getInsuranceIntervalByCarId(String carId) async {
    try {
      final response = await _client
          .from(DatabaseSchema.insuranceIntervals)
          .select()
          .eq(DatabaseSchema.carId, carId)
          .maybeSingle();

      if (response == null) return null;

      return InsuranceIntervalModel.fromJson(response);
    } catch (e) {
      throw Exception('Failed to get insurance interval: $e');
    }
  }

  /// Get all insurance intervals
  Future<List<InsuranceIntervalModel>> getAllInsuranceIntervals() async {
    try {
      final response = await _client
          .from(DatabaseSchema.insuranceIntervals)
          .select()
          .order(DatabaseSchema.createdAt, ascending: false);

      return (response as List)
          .map((json) => InsuranceIntervalModel.fromJson(json))
          .toList();
    } catch (e) {
      throw Exception('Failed to get insurance intervals: $e');
    }
  }

  /// Create a new insurance interval
  Future<InsuranceIntervalModel> createInsuranceInterval(
    InsuranceIntervalModel interval,
  ) async {
    try {
      final data = interval.toJson();
      // Remove 'id' as it's generated by the database
      data.remove('id');
      // Set created_at and updated_at
      data[DatabaseSchema.createdAt] = DateTime.now().toIso8601String();
      data[DatabaseSchema.updatedAt] = DateTime.now().toIso8601String();

      final response = await _client
          .from(DatabaseSchema.insuranceIntervals)
          .insert(data)
          .select()
          .single();

      return InsuranceIntervalModel.fromJson(response);
    } catch (e) {
      throw Exception('Failed to create insurance interval: $e');
    }
  }

  /// Update an existing insurance interval
  Future<InsuranceIntervalModel> updateInsuranceInterval(
    InsuranceIntervalModel interval,
  ) async {
    try {
      final data = interval.toJson();
      data[DatabaseSchema.updatedAt] = DateTime.now().toIso8601String();

      final response = await _client
          .from(DatabaseSchema.insuranceIntervals)
          .update(data)
          .eq(DatabaseSchema.id, interval.id)
          .select()
          .single();

      return InsuranceIntervalModel.fromJson(response);
    } catch (e) {
      throw Exception('Failed to update insurance interval: $e');
    }
  }

  /// Delete an insurance interval
  Future<void> deleteInsuranceInterval(String id) async {
    try {
      await _client
          .from(DatabaseSchema.insuranceIntervals)
          .delete()
          .eq(DatabaseSchema.id, id);
    } catch (e) {
      throw Exception('Failed to delete insurance interval: $e');
    }
  }
}

